# Generated by Django 4.0.5 on 2022-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndHabit', models.TextField()),
                ('IndValue', models.IntegerField()),
            ],
        ),
    ]
